/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as SessionSessionIdCompleteRouteImport } from './routes/session.$sessionId_.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdCompleteRoute =
  SessionSessionIdCompleteRouteImport.update({
    id: '/session/$sessionId_/complete',
    path: '/session/$sessionId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId/complete': typeof SessionSessionIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId/complete': typeof SessionSessionIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId_/complete': typeof SessionSessionIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session/$sessionId' | '/session/$sessionId/complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session/$sessionId' | '/session/$sessionId/complete'
  id: '__root__' | '/' | '/session/$sessionId' | '/session/$sessionId_/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionSessionIdCompleteRoute: typeof SessionSessionIdCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId_/complete': {
      id: '/session/$sessionId_/complete'
      path: '/session/$sessionId/complete'
      fullPath: '/session/$sessionId/complete'
      preLoaderRoute: typeof SessionSessionIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionSessionIdCompleteRoute: SessionSessionIdCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
